version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=123'
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres